### ISSUE TITLE
LibK not respecting field order in model

### ISSUE THREAD

**Issue by kaiaverkvist** [Kamshak/LibK#36]
Is this something we can get added support for?

**Comment by Kamshak** [comment]
Could you help me understand the issue a bit? What do you mean by field order?

**Comment by kaiaverkvist** [comment]
If I define a model like this:
![bilde](https://user-images.githubusercontent.com/36230927/102530859-d4db8280-40a1-11eb-9ee6-a65c5f05c463.png)

Then field order isn't preserved, causing weird UX inside of for instance phpmyadmin
![bilde](https://user-images.githubusercontent.com/36230927/102530915-e3c23500-40a1-11eb-959d-54d61446f8e8.png)

**Comment by Kamshak** [comment]
That makes sense, I think it's because for key-value tables lua does not preserve the order, so we would need to use something like an array instead 

``` 
fields: {
  { name = "variables", type = "table" },
  { name = "created", type = "createdTime" }
}
```

I don't think there's an easy solution here without changing the API a lot and making it incompatible with previous versions 😢 
The current API is a bit less typing and a easier to parse quickly with your eyes, too.

If there are no issues with field order for actual interaction with the db through code and it's only for coding, I believe there should be a way for you to reorder them in phpMyAdmin. It's definitely annoying but you should only have to do it once
